[package]
name = "gamy"
version = "0.1.0"
authors = ["2pac <tarasyarema@pm.me>"]
edition = "2018"

[dependencies]
glutin = "0.24"
winit = "0.20.0"
takeable-option = "0.4"
image = "0.21"

[build-dependencies]
gl_generator = "0.13"
